<?php

use App\Http\Controllers\Auth\AuthenticatedSessionController;
use App\Http\Controllers\AccountController;
use App\Http\Controllers\BalanceSheetReportController;
use App\Http\Controllers\CashFlowReportController;
use App\Http\Controllers\AccountsPayableReportController;
use App\Http\Controllers\AccountsReceivableReportController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\CustomerReceivableController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DebitNoteController;
use App\Http\Controllers\DocumentOutputController;
use App\Http\Controllers\FiscalPeriodController;
use App\Http\Controllers\IncomeStatementReportController;
use App\Http\Controllers\JournalEntryController;
use App\Http\Controllers\PosSaleController;
use App\Http\Controllers\PriceCategoryController;
use App\Http\Controllers\ProductCatalogTransferController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\PurchaseOrderController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\ShopController;
use App\Http\Controllers\ManifestController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\ThemeStylesController;
use App\Http\Controllers\StockTransferController;
use App\Http\Controllers\SupplierBillController;
use App\Http\Controllers\CreditNoteController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TrialBalanceReportController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\UserInterfacePreferenceController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/login')->name('home');
Route::get('/manifest.json', ManifestController::class)->name('manifest');
Route::get('/theme.css', ThemeStylesController::class)->name('theme.css');
Route::get('/shared-documents/{token}', [DocumentOutputController::class, 'shared'])->name('documents.shared');

Route::middleware('guest')->group(function (): void {
    Route::get('/login', [AuthenticatedSessionController::class, 'create'])->name('login');
    Route::post('/login', [AuthenticatedSessionController::class, 'store'])->name('login.store');
});

Route::middleware('auth')->group(function (): void {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::post('/user-interface-preferences', [UserInterfacePreferenceController::class, 'update'])->name('user-interface-preferences.update');
    Route::get('/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/reports/trial-balance', [TrialBalanceReportController::class, 'index'])->name('reports.trial-balance');
    Route::get('/reports/ap-aging', [AccountsPayableReportController::class, 'index'])->name('reports.ap-aging');
    Route::get('/reports/ar-aging', [AccountsReceivableReportController::class, 'index'])->name('reports.ar-aging');
    Route::get('/reports/balance-sheet', [BalanceSheetReportController::class, 'index'])->name('reports.balance-sheet');
    Route::get('/reports/income-statement', [IncomeStatementReportController::class, 'index'])->name('reports.income-statement');
    Route::get('/reports/cash-flow', [CashFlowReportController::class, 'index'])->name('reports.cash-flow');
    Route::get('/fiscal-periods', [FiscalPeriodController::class, 'index'])->name('fiscal-periods.index');
    Route::post('/fiscal-periods/{period}/close', [FiscalPeriodController::class, 'close'])->name('fiscal-periods.close');
    Route::post('/fiscal-periods/{period}/reopen', [FiscalPeriodController::class, 'reopen'])->name('fiscal-periods.reopen');
    Route::get('/pos/sales', [PosSaleController::class, 'index'])->name('pos.sales');
    Route::get('/documents/{type}/{id}/print', [DocumentOutputController::class, 'print'])->name('documents.print');
    Route::post('/documents/{type}/{id}/share', [DocumentOutputController::class, 'share'])->name('documents.share');
    Route::post('/documents/{type}/{id}/email', [DocumentOutputController::class, 'email'])->name('documents.email');
    Route::get('/document-shares', [DocumentOutputController::class, 'shares'])->name('document-shares.index');
    Route::post('/document-shares/{share}/revoke', [DocumentOutputController::class, 'revoke'])->name('document-shares.revoke');
    Route::get('/settings', SettingsController::class)->name('settings.index');
    Route::resource('shops', ShopController::class)->only(['index', 'create', 'edit']);
    Route::resource('warehouses', WarehouseController::class)->only(['index', 'create', 'edit']);
    Route::resource('units', UnitController::class)->only(['index', 'create', 'edit']);
    Route::resource('price-categories', PriceCategoryController::class)->only(['index', 'create', 'edit']);
    Route::get('/products/import', [ProductCatalogTransferController::class, 'import'])->name('products.import');
    Route::post('/products/import/preview', [ProductCatalogTransferController::class, 'preview'])->name('products.import.preview');
    Route::post('/products/import/confirm', [ProductCatalogTransferController::class, 'confirm'])->name('products.import.confirm');
    Route::get('/products/export', [ProductCatalogTransferController::class, 'export'])->name('products.export');
    Route::resource('products', ProductController::class)->only(['index', 'create', 'edit']);
    Route::resource('users', UserController::class)->only(['index', 'create', 'edit']);
    Route::resource('suppliers', SupplierController::class)->only(['index', 'create', 'edit']);
    Route::resource('customers', CustomerController::class)->only(['index', 'create', 'edit']);
    Route::resource('purchase-orders', PurchaseOrderController::class)->only(['index', 'create', 'edit']);
    Route::resource('supplier-bills', SupplierBillController::class)->only(['index']);
    Route::get('/supplier-bills/{supplierBill}/payments/create', [SupplierBillController::class, 'createPayment'])->name('supplier-bills.payments.create');
    Route::get('/credit-notes', [CreditNoteController::class, 'index'])->name('credit-notes.index');
    Route::get('/credit-notes/create', [CreditNoteController::class, 'create'])->name('credit-notes.create');
    Route::post('/credit-notes', [CreditNoteController::class, 'store'])->name('credit-notes.store');
    Route::get('/debit-notes', [DebitNoteController::class, 'index'])->name('debit-notes.index');
    Route::get('/debit-notes/create', [DebitNoteController::class, 'create'])->name('debit-notes.create');
    Route::post('/debit-notes', [DebitNoteController::class, 'store'])->name('debit-notes.store');
    Route::get('/customer-receivables', [CustomerReceivableController::class, 'index'])->name('customer-receivables.index');
    Route::get('/customer-receivables/{sale}/payments/create', [CustomerReceivableController::class, 'createPayment'])->name('customer-receivables.payments.create');
    Route::post('/customer-receivables/{sale}/payments', [CustomerReceivableController::class, 'storePayment'])->name('customer-receivables.payments.store');
    Route::resource('accounts', AccountController::class)->only(['index', 'create', 'edit']);
    Route::resource('journal-entries', JournalEntryController::class)->only(['index', 'create']);
    Route::resource('stock-transfers', StockTransferController::class)->only(['index', 'create']);
    Route::post('/logout', [AuthenticatedSessionController::class, 'destroy'])->name('logout');
});
